### ISSUE TITLE
[BUG] Parse error: Failed to parse operation

### ISSUE THREAD

**Issue by screendriver** [khaosdoctor/gotql#28]
**Describe the bug**

I try to create a mutation that looks like this:

```ts
const mutation = {
  operation: {
    name: 'updateSomething',
    args: {
      id: '1234',
      data: {
        name: 'foo',
        status: 'bar',
      },
    },
    fields: ['test'],
  },
};
```

and I'm calling it like this

```ts
const result = await gotQl.mutation(endpoint, mutation, {
  headers: {
    Authorization: `Bearer ${secret}`,
  },
});
```

But I get following runtime error:

```sh
Error: Runner error: Error when executing query: Parse error: Failed to parse operation "updateSomething" => varName.indexOf is not a function
    at Object.<anonymous> (/Users/myproject/node_modules/gotql/dist/modules/runner.js:122:19)
    at Generator.next (<anonymous>)
    at /Users/myproject/node_modules/gotql/dist/modules/runner.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/myproject/node_modules/gotql/dist/modules/runner.js:4:12)
    at Object.run (/Users/myproject/node_modules/gotql/dist/modules/runner.js:103:12)
    at Object.mutation (/Users/myproject/node_modules/gotql/dist/mutation.js:23:21)
    at update (/Users/myproject/myscript.js:35:32)
    at Object.<anonymous> (/Users/myproject/myscript.js:43:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```

**Comment by khaosdoctor** [comment]
I'm going to take a look at this tomorrow!

**Comment by khaosdoctor** [comment]
So I got a glimpse of what might be the issue here. The thing is that GotQL does not allow for nested argument lists, it's a type issue that could be resolved by turning this:

```ts
export type QueryOperation = {
  name: string
  args?: {
    [name: string]: string | ArgObject
  },
  alias?: string
  fields: Array<string | FieldObject>
}

export type ArgObject = {
  [name: string]: string | ArgObject
} | {
  value: string
  escape: boolean
}
```

Into this:

```ts
export type QueryOperation = {
  name: string
  args?: {
    [name: string]: string | ArgObject
  }
  alias?: string
  fields: Array<string | FieldObject>
}

export type ArgObject = {
  value: any
  escape: boolean
}
```

Which removes the allowance of recursive nested arguments. However, the spec does allow the use of argument objects, so I'll be adding this support to the framework

**Comment by khaosdoctor** [comment]
Done! Sorry about the delay on this, @screendriver I got a bit busy over here 😅 

I hope this fixes your issue!

**Comment by screendriver** [comment]
No problem. Awesome, thanks :+1:
